release:
  image: ubuntu
  only:
    - tags
  script:
    - apt-get update -y
    - apt-get install make zip -y
    - make pack
  artifacts:
    untracked: false
    when: on_success
    paths:
      - "miguel-*.zip"
