version: '3.7'
services:
  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - ./run/mysql_data:/var/lib/mysql

  prestashop:
    image: prestashop/prestashop:1.7
    ports:
      - '8082:80'
    environment:
      - DB_SERVER=mysql
      - PS_DOMAIN=localhost:8082
    volumes:
      - ./run/ps_data:/var/www/html
      - ./miguel:/var/www/html/modules/miguel
    depends_on:
      - mysql

  adminer:
    image: adminer
    ports:
      - '8083:8080'
    depends_on:
      - mysql
