name: PHP tests
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize, edited]

permissions:
  checks: write

jobs:
  header-stamp:
    name: Check license headers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Cache vendor folder
        uses: actions/cache@v3
        with:
          path: vendor
          key: php-${{ hashFiles('composer.lock') }}

      - name: Cache composer folder
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: php-composer-cache

      - run: composer install

      - name: Run Header Stamp in Dry Run mode
        run: php vendor/bin/header-stamp --license=LICENSE.txt --exclude=.github,node_modules,vendor,tests,_dev,run,composer.json --dry-run
  php-linter:
    name: PHP Syntax check 7.2|7.3|7.4|8.0|8.1|8.2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: PHP syntax checker 7.2
        uses: prestashop/github-action-php-lint/7.2@master
      - name: PHP syntax checker 7.3
        uses: prestashop/github-action-php-lint/7.3@master
      - name: PHP syntax checker 7.4
        uses: prestashop/github-action-php-lint/7.4@master
      - name: PHP syntax checker 8.0
        uses: prestashop/github-action-php-lint/8.0@master
      - name: PHP syntax checker 8.1
        uses: prestashop/github-action-php-lint/8.1@master
      - name: PHP syntax checker 8.2
        uses: prestashop/github-action-php-lint/8.2@master
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache vendor folder
        uses: actions/cache@v3
        with:
          path: vendor
          key: php-${{ hashFiles('composer.lock') }}

      - name: Cache composer folder
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: php-composer-cache

      - run: composer install --prefer-dist --no-progress --no-ansi --no-interaction

      - name: Run PHP CS Fixer
        run: vendor/bin/php-cs-fixer fix --dry-run --diff --verbose

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        presta-versions: ['1.7', '8.0', 'latest']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache vendor folder
        uses: actions/cache@v3
        with:
          path: vendor
          key: php-${{ hashFiles('composer.lock') }}

      - name: Cache composer folder
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: php-composer-cache

      - run: composer install --prefer-dist --no-progress --no-ansi --no-interaction

      - name: Pull PrestaShop files (Tag ${{ matrix.presta-versions }})
        run: docker run -tid --rm -v ps-volume:/var/www/html --name temp-ps prestashop/prestashop:${{ matrix.presta-versions }}

      - name : Run PHPStan
        run: docker run --rm --volumes-from temp-ps -v $PWD:/web/module -e _PS_ROOT_DIR_=/var/www/html --workdir=/web/module ghcr.io/phpstan/phpstan:1 analyse --configuration=/web/module/tests/phpstan/phpstan.neon --error-format github
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - php-version: '7.1'
            prestashop-version: '1.7.7.8'
            phpunit-version: '7.5.20'
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: 'password'
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
          tools: composer:v2, phpunit:${{ matrix.phpunit-version }}
          extensions: gd, mbstring, zip, mcrypt, pdo_mysql, dom

      - name: Start mysql service
        run: sudo /etc/init.d/mysql start
      - name: Status mysql service
        run: sudo systemctl status mysql

      - name: Test MySQL Connection
        run: mysql -u root -h '127.0.0.1' --password=password --port ${{ job.services.mysql.ports[3306] }} -e "show databases"

      - name: Cache Prestashop installation
        uses: actions/cache@v3
        with:
          path: vendor2/PrestaShop
          key: prestashop-${{ matrix.prestashop-version }}-${{ matrix.php-version }}

      - name: Install PrestaShop
        run: bash .github/scripts/install-prestashop.sh
        env:
          PRESTASHOP_VERSION: ${{ matrix.prestashop-version }}
          MYSQL_PORT: ${{ job.services.mysql.ports[3306] }}

      - name: Run PHPUnit
        run: phpunit -c ./tests/Unit/phpunit.xml
